trigger:
  batch: true
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - openshift/template.yaml

pool:
  vmImage: 'ubuntu-16.04'

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.cache/yarn
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository/
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -Xmx3072m'
  QUARKUS_LOCAL_REPO: $(MAVEN_CACHE_FOLDER)

steps:
- task: CacheBeta@0
  inputs:
    key: yarn | $(Agent.OS) | ./src/main/frontend/yarn.lock
    path: $(YARN_CACHE_FOLDER)
  displayName: Cache Yarn packages
- task: CacheBeta@0
  inputs:
    key: maven | pom.xml
    path: $(MAVEN_CACHE_FOLDER)
    securityNamespace: cache
  displayName: Cache Maven local repo
- task: Maven@3
  displayName: 'Maven Build'
  inputs:
    goals: 'clean package'
    jdkVersionOption: '1.8'
    options: ''